# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/calendrical',
                'doc_host': 'https://the-engi-nerd.github.io',
                'git_url': 'https://github.com/the-engi-nerd/calendrical',
                'lib_path': 'calendrical'},
  'syms': {'calendrical.core': {'calendrical.core.foo': ('core.html#foo', 'calendrical/core.py')}}}
