# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/calendrical',
                'doc_host': 'https://the-engi-nerd.github.io',
                'git_url': 'https://github.com/the-engi-nerd/calendrical',
                'lib_path': 'calendrical'},
  'syms': {'calendrical.prelude': {'calendrical.prelude.foo': ('prelude.html#foo', 'calendrical/prelude.py')}}}
